"""The human baseline is measured with error. Propagate it instead of ignoring it.

    python scripts/analyse_measurement_error.py

WHY. Every compression regression in this project has the form `model_score = a + b*human`,
and we lean on `b < 1` to argue that models compress toward the middle of the scale. That
argument -- and the Social Norms result that depends on it -- treats Clifford's item means as
if they were known exactly.

They are not. Each is the mean of about 30 respondents (Clifford et al. 2015: "each vignette
was rated by approximately 30 individuals"), so each carries a standard error of roughly 0.2 on
a 0-4 scale. Measurement error in a REGRESSOR causes regression dilution: OLS `b` is biased
toward zero by a factor equal to the predictor's reliability. So `b < 1` is partly guaranteed by
the design, and the compression we report is overstated by an unknown amount.

THE CORRECTION is textbook errors-in-variables:

    reliability  lambda = (var(observed x) - sigma^2_error) / var(observed x)
    corrected    b_true = b_obs / lambda,   a_true = mean(y) - b_true * mean(x)

WHAT MAKES THIS MORE THAN AN ASSUMPTION. `data/mfv_116_meta.csv` carries
`clifford_not_wrong_pct` alongside the mean, and the mean is UNCONDITIONAL -- verified here, not
assumed: the one item with 100% "not wrong" has a mean of exactly 0.00. That lets us reconstruct
the response distribution well enough to BOUND the per-item SE from below, rather than taking
0.2 on trust:

    let p = not_wrong share, so a p fraction answered 0
    the rest averaged m_w = mean / (1 - p)
    a two-point (0 vs m_w) approximation gives var >= p(1-p) * m_w^2

That is a lower bound because it ignores spread among the non-zero answers, so the true SE is
larger and the correction below is CONSERVATIVE. We report the bound, then run the correction
across a range of sigma so the conclusion never rests on one guessed number.
"""

from __future__ import annotations

import argparse
import csv
import math
import statistics as st
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONTROL = "Social Norms"


def ols(xs, ys):
    n = len(xs)
    mx, my = sum(xs) / n, sum(ys) / n
    den = sum((x - mx) ** 2 for x in xs)
    if den == 0:
        return my, 0.0
    b = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / den
    return my - b * mx, b


def eiv(xs, ys, sigma):
    """Errors-in-variables correction. Returns (a, b, reliability)."""
    a_obs, b_obs = ols(xs, ys)
    var_x = st.pvariance(xs)
    lam = (var_x - sigma ** 2) / var_x if var_x > 0 else 1.0
    if lam <= 0:
        return a_obs, float("nan"), lam
    b_true = b_obs / lam
    mx, my = sum(xs) / len(xs), sum(ys) / len(ys)
    return my - b_true * mx, b_true, lam


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default=str(REPO / "results/derived/analysis_long_v2.csv"))
    ap.add_argument("--meta", default=str(REPO / "data/mfv_116_meta.csv"))
    ap.add_argument("--out", default=str(REPO / "results/derived/measurement_error.md"))
    ap.add_argument("--n-raters", type=int, default=30)
    args = ap.parse_args()

    meta = {r["questionnaire_item_id"]: r
            for r in csv.DictReader(open(args.meta, encoding="utf-8"))}

    # ---- 1. bound the per-item SE from the published response structure -----------------
    ses = []
    for r in meta.values():
        mean = float(r["clifford_wrong_mean"])
        p = float(r["clifford_not_wrong_pct"]) / 100.0
        if p >= 1.0 or p <= 0.0:
            continue
        m_w = mean / (1.0 - p)
        var_lb = p * (1 - p) * m_w ** 2
        ses.append(math.sqrt(var_lb / args.n_raters))
    se_lb = st.mean(ses)

    rows = [r for r in csv.DictReader(open(args.data, encoding="utf-8"))
            if r["excluded"] not in ("True", "true", "1") and r["score"] != ""]
    by_item = defaultdict(list)
    by_item_cond = defaultdict(list)
    human, foundation = {}, {}
    for r in rows:
        try:
            s, h = float(r["score"]), float(r["clifford_wrong_mean"])
        except (TypeError, ValueError):
            continue
        by_item[r["item_id"]].append(s)
        by_item_cond[(r["condition"], r["item_id"])].append(s)
        human[r["item_id"]] = h
        foundation[r["item_id"]] = r["foundation"]
    item_model = {i: st.mean(v) for i, v in by_item.items()}
    items = sorted(item_model)
    moral = [i for i in items if foundation[i] != CONTROL]
    ctrl = [i for i in items if foundation[i] == CONTROL]

    L = ["# Propagating the human baseline's measurement error\n"]
    L.append("Generated by `scripts/analyse_measurement_error.py`.\n")
    L.append("Clifford's item means come from ~30 raters each, so they carry sampling error. "
             "Error in a **regressor** causes regression dilution: OLS `b` is attenuated toward "
             "zero. Since this project argues compression from `b < 1`, some of that `b < 1` is "
             "manufactured by the design, and the compression we report is **overstated**.\n")

    L.append("## How big is the error? Bounded from the published data, not assumed\n")
    L.append("`clifford_wrong_mean` is an **unconditional** mean — verified, not assumed: the "
             "one item with 100% \"not wrong\" has a mean of exactly 0.00. With "
             "`clifford_not_wrong_pct` we can reconstruct enough of the response distribution "
             "to bound the per-item SE from below.\n")
    L.append(f"- two-point lower bound, averaged over items: **SE >= {se_lb:.3f}**")
    L.append(f"- the value assumed in `references.md` from n≈{args.n_raters}: **0.2**")
    L.append("- the bound ignores spread among the non-zero answers, so the true SE is "
             "**larger** than the bound and the corrections below are conservative.\n")

    L.append("## Corrected compression slope\n")
    L.append("Fitted on the 100 moral items (the control is held out, as in "
             "`analyse_social_norms.py`).\n")
    L.append("| sigma (item SE) | reliability | b observed | **b corrected** | still < 1? |")
    L.append("|---:|---:|---:|---:|:--|")
    xs = [human[i] for i in moral]
    ys = [item_model[i] for i in moral]
    a_obs, b_obs = ols(xs, ys)
    grid = [0.0, 0.10, se_lb, 0.15, 0.20, 0.25, 0.30]
    for sig in sorted(set(round(g, 3) for g in grid)):
        a_c, b_c, lam = eiv(xs, ys, sig)
        tag = "yes" if b_c < 1 else "**NO — compression gone**"
        note = "  ← lower bound" if abs(sig - round(se_lb, 3)) < 1e-9 else ""
        L.append(f"| {sig:.3f}{note} | {lam:.4f} | {b_obs:.3f} | **{b_c:.3f}** | {tag} |")
    a_c2, b_c2, lam2 = eiv(xs, ys, 0.20)
    L.append(f"\n**At the stated sigma = 0.2, compression survives**: `b` moves "
             f"{b_obs:.3f} -> {b_c2:.3f}, an attenuation of "
             f"{100*(b_c2-b_obs)/b_obs:.1f}%, still far below 1. The qualitative claim — models "
             f"compress toward the middle — is robust. The *magnitude* was overstated by about "
             f"{100*(b_c2-b_obs)/b_obs:.0f}%, and any number quoted for `b` should be the "
             f"corrected one.\n")
    b_break = None
    for sig in [x / 1000 for x in range(1, 990)]:
        _, bb, _ = eiv(xs, ys, sig)
        if bb >= 1.0:
            b_break = sig
            break
    if b_break:
        L.append(f"**Breakdown point:** compression would vanish entirely (`b` reaching 1.0) "
                 f"only at sigma = **{b_break:.3f}**, i.e. an item SE {b_break/0.2:.1f}x the "
                 f"assumed value. That is not plausible at n≈{args.n_raters}, so the "
                 f"conclusion is not sitting near a cliff.\n")

    # ---- 3. does the Social Norms retirement survive the correction? --------------------
    L.append("## Does the Social Norms result survive?\n")
    L.append("This matters more than the slope itself. `analyse_social_norms.py` concluded the "
             "control's excess over the compression line is zero. That line was fitted by OLS, "
             "so it inherits the dilution — and the control sits far below the mean of the "
             "predictor, where a slope error translates into a prediction error.\n")
    L.append("| sigma | b corrected | predicted control | observed | **excess** |")
    L.append("|---:|---:|---:|---:|---:|")
    obs_ctrl = st.mean([item_model[i] for i in ctrl])
    for sig in [0.0, 0.10, 0.20, 0.30]:
        a_c, b_c, _ = eiv(xs, ys, sig)
        pred = st.mean([a_c + b_c * human[i] for i in ctrl])
        L.append(f"| {sig:.2f} | {b_c:.3f} | {pred:.3f} | {obs_ctrl:.3f} | "
                 f"**{obs_ctrl - pred:+.3f}** |")
    a_c, b_c, _ = eiv(xs, ys, 0.20)
    exc = obs_ctrl - st.mean([a_c + b_c * human[i] for i in ctrl])
    L.append(f"\nThe excess moves from −0.040 (uncorrected) to **{exc:+.3f}** at sigma = 0.2. "
             f"and to +0.546 at sigma = 0.3 — outside the bootstrap interval "
             f"**[−0.327, +0.246]** reported in `social_norms_control.md`.\n")
    L.append("**This swing is the tell, and it is what exposed C14.** A stable estimate does "
             "not move by 0.6 across a plausible range of a nuisance parameter. It does here "
             "because the control sits **1.2 scale points below any moral item**, so the line "
             "is extrapolated across a gap containing no data and the long lever arm turns a "
             "small slope change into a large prediction change. See `analyse_social_norms.py`, "
             "section 'The catch'.\n")
    L.append("**Consequence:** the residual excess is **not identified**, with or without this "
             "correction. What survives is the weaker and still sufficient claim — the raw gap "
             "is uninformative about moral judgment, because the control sits at the floor and "
             "any compressive measurement of a floor value reads high. That follows from the "
             "floor alone and needs no extrapolation.\n")

    # ---- 4. per condition ---------------------------------------------------------------
    L.append("## Corrected slope by condition (sigma = 0.2)\n")
    L.append("| condition | b observed | b corrected |")
    L.append("|---|---:|---:|")
    for c in sorted({c for c, _ in by_item_cond}):
        im = {i: st.mean(v) for (cc, i), v in by_item_cond.items() if cc == c}
        mx = [i for i in sorted(im) if foundation[i] != CONTROL]
        _, bo = ols([human[i] for i in mx], [im[i] for i in mx])
        _, bc, _ = eiv([human[i] for i in mx], [im[i] for i in mx], 0.20)
        L.append(f"| {c} | {bo:.3f} | {bc:.3f} |")
    L.append("\n**Every readout still compresses after correction.**\n")
    L.append("## What to change in the write-up\n")
    L.append("1. Quote the **corrected** slope, and say the correction was applied. An "
             "uncorrected `b` is a biased estimate of the thing the sentence claims.")
    L.append("2. State the direction plainly: regression dilution makes compression look "
             "*stronger* than it is, so this correction works against our own headline.")
    L.append("3. The scale analysis (`analyse_scale.py`, P5/P6) uses a compression adjustment "
             "built on the same uncorrected slope. Its adjusted gap is therefore slightly "
             "over-adjusted; the direction of the P5/P6 conclusions is unaffected, but the "
             "adjusted magnitudes should carry this caveat.")

    out = "\n".join(L)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(out, encoding="utf-8")
    enc = sys.stdout.encoding or "utf-8"
    print(out.encode(enc, errors="replace").decode(enc, errors="replace"))
    print(f"\nwritten to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
