"""Is greedy decoding actually reproducible across runs? Measured, not assumed.

    python scripts/audit_greedy_determinism.py
    python scripts/audit_greedy_determinism.py --out results/derived/greedy_determinism.md

WHY THIS EXISTS. `METHODS_EXPLAINER.md` s3 calls greedy "deterministic in principle" and
flags -- without testing -- that GPU floating-point reduction order can vary with batch
composition, so bit-identical output across differently batched runs is not guaranteed.
`LIMITATIONS.md` s12 records the same caveat as FLAGGED BUT NOT VERIFIED. It was corrected
once already, on 2026-08-09, because METHODS_EXPLAINER had falsely claimed we verified it.

We can verify it now for free, with no GPU, because the v1 and v2 collections independently
ran greedy on the same 20 models. The comparison is close to ideal:

  - byte-identical rendered prompt (asserted here per item via prompt_sha, not assumed)
  - same GPU model, same vllm / transformers / torch versions (asserted here from manifests)
  - what DID change: v2 runs six conditions where v1 ran four, so batch composition differs

That is exactly the perturbation the caveat names. What this CANNOT do is isolate batch
composition from every other harness difference between v1 and v2 -- it establishes that
greedy is not reproducible across runs, not precisely why. Stated that way in the output.

Two numbers, and the distinction between them is the whole point: raw text drift is
cosmetic if the parser recovers the same digit, so the number that matters for the analysis
is how often the SCORE moves.
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
import statistics
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def load(path: str) -> list[dict]:
    with open(path, encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def manifest(csv_path: str) -> dict:
    man = csv_path[:-4] + ".manifest.json"
    if not os.path.exists(man):
        return {}
    try:
        with open(man, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw", type=Path, default=REPO / "results" / "raw")
    ap.add_argument("--condition", default="greedy")
    ap.add_argument("--out", type=Path,
                    default=REPO / "results" / "derived" / "greedy_determinism.md")
    args = ap.parse_args()

    v1: dict[str, str] = {}
    v2: dict[str, str] = {}
    for p in sorted(glob.glob(str(args.raw / "*.csv"))):
        stem = os.path.basename(p)[:-4]
        (v2 if stem.endswith("_v2") else v1)[stem.replace("_v2", "")] = p
    common = sorted(set(v1) & set(v2))
    if not common:
        print("no models present in both collections")
        return 1

    env_v1 = {json.dumps(manifest(v1[m]).get("packages"), sort_keys=True) for m in common}
    env_v2 = {json.dumps(manifest(v2[m]).get("packages"), sort_keys=True) for m in common}
    gpus = {manifest(v1[m]).get("gpu") for m in common} | {manifest(v2[m]).get("gpu")
                                                           for m in common}
    same_env = env_v1 == env_v2 and len(env_v1) == 1

    total = text_diff = score_diff = skipped = 0
    per_model_text: Counter = Counter()
    per_model_score: Counter = Counter()
    shifts: list[float] = []
    examples: list[tuple[str, str, str, str]] = []

    for m in common:
        a = {r["item_id"]: r for r in load(v1[m]) if r["condition"] == args.condition}
        b = {r["item_id"]: r for r in load(v2[m]) if r["condition"] == args.condition}
        for item, ra in a.items():
            rb = b.get(item)
            if rb is None:
                continue
            # The comparison is only meaningful if the model saw the same bytes. Assert it.
            if ra["prompt_sha"] != rb["prompt_sha"]:
                skipped += 1
                continue
            total += 1
            ta = (ra.get("raw_output") or "").strip()
            tb = (rb.get("raw_output") or "").strip()
            if ta != tb:
                text_diff += 1
                per_model_text[m] += 1
                if len(examples) < 8:
                    examples.append((m, item, ta[:90], tb[:90]))
            if ra["score"] != rb["score"]:
                score_diff += 1
                per_model_score[m] += 1
                try:
                    shifts.append(abs(float(ra["score"]) - float(rb["score"])))
                except (TypeError, ValueError):
                    pass

    pct = lambda n: f"{n / total:.2%}" if total else "n/a"
    L: list[str] = []
    L.append(f"# Is `{args.condition}` reproducible across runs? — measured\n")
    L.append("Generated by `scripts/audit_greedy_determinism.py`. No GPU required: this "
             "compares the v1 and v2 collections, which independently ran the same models.\n")
    L.append("## Controls\n")
    L.append(f"- models in both collections: **{len(common)}**")
    L.append(f"- cells compared, byte-identical prompt asserted per item: **{total}**")
    L.append(f"- cells skipped because the prompt differed: **{skipped}**")
    L.append(f"- GPU model(s) across both runs: {', '.join(sorted(str(g) for g in gpus))}")
    L.append(f"- package versions identical across the two collections: "
             f"**{'yes' if same_env else 'NO — interpret with care'}**")
    if same_env:
        L.append(f"  - `{sorted(env_v1)[0]}`")
    L.append("- what deliberately differs: v2 runs six conditions where v1 ran four, so "
             "**batch composition differs**. That is the perturbation the caveat names.\n")
    L.append("## Result\n")
    L.append(f"| | count | share |")
    L.append(f"|---|---:|---:|")
    L.append(f"| raw text differs | {text_diff} | **{pct(text_diff)}** |")
    L.append(f"| parsed score differs | {score_diff} | **{pct(score_diff)}** |")
    if shifts:
        L.append(f"\nWhere the score moved: mean |shift| **{statistics.mean(shifts):.3f}**, "
                 f"max **{max(shifts):.3f}** on a 0–4 scale.\n")
    L.append("**Text drift is largely cosmetic — the parser recovers the same digit from "
             "`\"3\"` and `\"3: Very wrong\"`. The score column is the one that reaches the "
             "analysis.**\n")
    L.append("## Verdict\n")
    if score_diff == 0:
        L.append(f"`{args.condition}` reproduced exactly on every comparable cell.")
    else:
        L.append(f"**`{args.condition}` is NOT reproducible across runs.** The caveat flagged "
                 f"in `METHODS_EXPLAINER.md` §3 and `LIMITATIONS.md` §12 is real and now "
                 f"measured: {pct(score_diff)} of scores move between two runs of the same "
                 f"model, on the same prompt, same GPU model and same package versions.\n")
        L.append("**What this does and does not establish.** It establishes that a "
                 "'deterministic' arm is not reproducible run-to-run. It does *not* isolate "
                 "batch composition as the cause — v1 and v2 differ in more than batching — "
                 "so the mechanism remains the documented hypothesis, not a demonstrated "
                 "one. Ruling out the obvious alternatives (prompt, GPU model, library "
                 "versions) is what the Controls section above is for.\n")
        L.append("**Consequence for the design.** Of the arms described as deterministic, "
                 "greedy is the one that generates text, and generation is where the "
                 "instability lives. Re-running it is therefore not 'measuring a ruler "
                 "twice' — a claim `METHODS_EXPLAINER.md` §5 makes about the deterministic "
                 "arms collectively and which does not hold for this one.\n")
    if per_model_score:
        L.append("## Models whose greedy SCORE moved\n")
        L.append("| model | items changed / 116 |")
        L.append("|---|---:|")
        for m, c in per_model_score.most_common():
            L.append(f"| {m} | {c} |")
        L.append("")
    if examples:
        L.append("## Example text divergences\n")
        for m, item, ta, tb in examples:
            L.append(f"- **{m}**, item {item}\n  - v1: `{ta}`\n  - v2: `{tb}`")
        L.append("")

    out = "\n".join(L)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(out, encoding="utf-8")
    print(out)
    print(f"\nwritten to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
