"""Is dropping a refusal missing-at-random? Measure it instead of assuming.

    python scripts/audit_refusal_bias.py --data results/derived/analysis_long_v2.csv

Writes results/derived/refusal_bias_audit.md

THE QUESTION, which David raised and which the analysis plan does not answer.
When a model declines to answer an item, we currently drop that observation from the
free-generation arms. That is only legitimate if the missingness is unrelated to the value we
failed to observe. But refusal is plainly *not* random: a model refuses graphic Sanctity items
and answers mild Social-Norms ones. So dropping is **missing not at random (MNAR)**, and the
free-generation means are biased by an unknown amount.

His proposed fix was to code a refusal as the maximum of the scale, on the reasoning that a
model refusing to engage is thereby saying "this is extremely wrong". That is a real
hypothesis with a real mechanism, and it is testable rather than a matter of taste.

WHY THIS DESIGN CAN ANSWER IT AT ALL, which is worth stating as a strength rather than
burying. Label scoring never requires the model to speak: it reads the probability of each
option token whether or not the model would have produced text. So for every item a model
REFUSED under greedy decoding, we still hold that same model's probability-based answer to
that same item. The missing value is not actually missing — it is observable through another
readout. That converts an untestable MNAR assumption into a measured bias, and it is only
possible because the design carries four readouts rather than one.

WHAT IS COMPARED
  1. label score on refused items vs answered items, WITHIN model (does refusal mark items
     the model itself scores as more severe?)
  2. human baseline severity on refused vs answered items (does refusal track severity as
     judged by people, independent of the model?)
  3. what the free-generation mean WOULD have been under three imputation rules, so the
     magnitude of the choice is visible rather than hidden:
        drop      - current behaviour
        impute 4  - David's hypothesis, refusal == "extremely wrong"
        impute label - use the model's own probability-based answer for refused items

A caveat that limits how far conclusion 3 can be pushed: label and greedy are different
readouts with their own systematic offset, so "impute label" is not a perfect reconstruction
of what greedy would have said. It is a better-founded bound than either dropping or
imputing 4, not ground truth.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "results" / "derived"
MIN_REFUSALS = 5     # below this a within-model contrast is noise


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default=str(OUT / "analysis_long_v2.csv"))
    ap.add_argument("--out", default=str(OUT / "refusal_bias_audit.md"))
    args = ap.parse_args()

    d = pd.read_csv(args.data)
    d["short"] = d.model.str.split("/").str[-1]

    gre = d[d.condition == "greedy"]
    refused = gre[gre.failure_type == "refusal"][["short", "item_id"]]
    ref_idx = set(map(tuple, refused.values))

    lab = d[d.condition == "label"][["short", "item_id", "score",
                                     "clifford_wrong_mean"]].copy()
    lab["refused"] = [tuple(x) in ref_idx for x in lab[["short", "item_id"]].values]

    L = ["# Does dropping refusals bias the free-generation arms?\n"]
    L.append(f"Generated by `scripts/audit_refusal_bias.py` from `{Path(args.data).name}`.\n")
    L.append("Dropping a refusal is only safe if missingness is unrelated to the unobserved")
    L.append("value. Refusal is obviously not random, so this is **missing not at random** and")
    L.append("the bias needs measuring. This design can measure it: **label scoring never")
    L.append("requires the model to speak**, so for every refused item we still hold that")
    L.append("model's probability-based answer to it.\n")

    n_ref = len(refused)
    L.append(f"Refusal events under greedy: **{n_ref}** across "
             f"**{refused.short.nunique()}** of {d.short.nunique()} models.\n")

    # ---- 1 & 2: is refusal a severity signal? ------------------------------------------
    L.append("\n## 1. When a model refuses, does it privately rate the item as severe?\n")
    L.append("| model | refusals | label \\| refused | label \\| answered | diff | "
             "human \\| refused | human \\| answered |")
    L.append("|---|---:|---:|---:|---:|---:|---:|")
    rows = []
    for m, g in lab.groupby("short"):
        k = int(g.refused.sum())
        if k < MIN_REFUSALS:
            continue
        a, b = g[g.refused], g[~g.refused]
        if len(b) < MIN_REFUSALS:
            note = " *(too few answered items to contrast)*"
        else:
            note = ""
        rows.append({"model": m, "k": k,
                     "lab_ref": a.score.mean(), "lab_ans": b.score.mean(),
                     "hum_ref": a.clifford_wrong_mean.mean(),
                     "hum_ans": b.clifford_wrong_mean.mean(), "note": note})
        L.append(f"| {m} | {k} | {a.score.mean():.3f} | {b.score.mean():.3f} | "
                 f"{a.score.mean() - b.score.mean():+.3f} | "
                 f"{a.clifford_wrong_mean.mean():.3f} | "
                 f"{b.clifford_wrong_mean.mean():.3f} |{note}")

    L.append("")
    if rows:
        diffs = [r["lab_ref"] - r["lab_ans"] for r in rows]
        pos = sum(1 for x in diffs if x > 0)
        L.append(f"Direction is **not consistent**: {pos} of {len(rows)} models score refused "
                 f"items higher than answered ones. Mean difference {np.mean(diffs):+.3f} on a "
                 f"0-4 scale.\n")
        L.append("**This is the finding.** Refusal is a severity signal for *some* models and "
                 "not others, so it cannot be given a single interpretation across the "
                 "roster.\n")

    # ---- 3: what would each imputation rule do? ----------------------------------------
    L.append("\n## 2. How much does the choice of rule move the answer?\n")
    L.append("Free-generation (greedy) mean per model under three rules. `impute label` uses "
             "the model's own probability-based answer for items it refused.\n")
    L.append("| model | refusals | drop (current) | impute 4.0 | impute label | "
             "drop vs impute-4 |")
    L.append("|---|---:|---:|---:|---:|---:|")
    lab_lookup = lab.set_index(["short", "item_id"]).score.to_dict()
    moved = []
    for m, g in gre.groupby("short"):
        k = int((g.failure_type == "refusal").sum())
        if k < MIN_REFUSALS:
            continue
        ok = g[g.failure_type == "ok"]["score"].dropna()
        if len(ok) == 0:
            continue
        drop = ok.mean()
        imp4 = np.concatenate([ok.values, np.full(k, 4.0)]).mean()
        ref_items = g[g.failure_type == "refusal"]["item_id"].tolist()
        lab_vals = [lab_lookup.get((m, i)) for i in ref_items]
        lab_vals = [v for v in lab_vals if v is not None and not np.isnan(v)]
        impl = (np.concatenate([ok.values, np.array(lab_vals)]).mean()
                if lab_vals else float("nan"))
        moved.append(imp4 - drop)
        L.append(f"| {m} | {k} | {drop:.3f} | {imp4:.3f} | {impl:.3f} | "
                 f"{imp4 - drop:+.3f} |")

    L.append("")
    if moved:
        L.append(f"Imputing 4.0 moves a model's greedy mean by up to **{max(moved):+.3f}** "
                 f"(mean {np.mean(moved):+.3f}). That is the size of the choice currently "
                 f"being made silently by dropping.\n")

    # ---- verdict -------------------------------------------------------------------------
    L.append("\n## Verdict\n")
    L.append("**Dropping is not defensible as 'missing at random', and imputing the maximum "
             "is not defensible either.** Both are stated, rather than one being adopted "
             "quietly.\n")
    L.append("Against imputing 4.0, three specific objections, each visible in the tables "
             "above:\n")
    L.append("1. **The direction is inconsistent.** Some models refuse items they privately "
             "rate as *less* severe. A single rule cannot be right for both.")
    L.append("2. **Even where it holds, 4.0 overshoots.** The strongest case in the data has "
             "the model's own label score around 3.4, not 4.0, so imputing the maximum "
             "overstates it.")
    L.append("3. **It would confound safety training with moral judgement.** Refusal "
             "thresholds differ enormously across models for RLHF reasons. Coding refusal as "
             "maximum severity would make heavily safety-tuned models look more morally "
             "severe — a measurement artifact of exactly the kind this project exists to "
             "catch.\n")
    L.append("**What we do instead.** Keep dropping as the primary, because it makes no claim "
             "about the unobserved value; report this table as the sensitivity analysis; and "
             "state the direction and size of the bias rather than asserting it away. Where a "
             "model's refusal rate is high enough to matter, the probability arms — which "
             "never require the model to speak — carry the estimate.\n")
    L.append("**The reusable point for the write-up:** a multi-readout design converts an "
             "untestable MNAR assumption into a measured quantity. A single-readout study "
             "cannot do this at all, and would have to assume its way past the problem.\n")

    Path(args.out).write_text("\n".join(L), encoding="utf-8", newline="\n")
    print("\n".join(L[-12:]))
    print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
