"""The excluded-cells table — a pre-specified deliverable that was never produced.

    docs/ANALYSIS_PLAN.md:191   "Everything reported **with and without** exclusions, plus a
                                 table of what was dropped."
    docs/state.md:435-436       "Everything is reported with and without the exclusions. The
                                 excluded cells are listed in a table with their rates and
                                 reasons."

Both halves were committed to before the confirmatory run. The WITH/WITHOUT half was computed
-- `variance_ratio_v2.csv` carries `exclusions=True` and `exclusions=False` rows for every
foundation -- but never reported in any write-up document. The TABLE half was never produced at
all. Found 2026-08-15 by auditing the pre-specified commitments against the artifact directory,
which is a sweep nothing in this repo had run: every previous pass checked claims against DATA,
so a commitment with no number attached had nothing to fail against.

This script produces both halves. It is descriptive only and decides nothing.

    python scripts/report_exclusions.py                       # v2 (default)
    python scripts/report_exclusions.py --data <long.csv>
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parent.parent
DERIVED = REPO / "results" / "derived"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--data", default=str(DERIVED / "analysis_long_v2.csv"),
                    help="long-form dataset (default: analysis_long_v2.csv)")
    ap.add_argument("--variance-ratio", default=None,
                    help="variance-ratio CSV for the with/without table "
                         "(default: derived from --data)")
    ap.add_argument("--out", default=None, help="output markdown (default derived from --data)")
    args = ap.parse_args()

    data_path = Path(args.data)
    sfx = "_v2" if "_v2" in data_path.name else ""
    vr_path = Path(args.variance_ratio) if args.variance_ratio else \
        DERIVED / f"variance_ratio{sfx}.csv"
    out_path = Path(args.out) if args.out else DERIVED / f"exclusions{sfx}.md"

    df = pd.read_csv(data_path)
    df["excluded"] = df["excluded"].astype(str) == "True"

    L: list[str] = []
    def p(s: str = "") -> None:
        L.append(s)

    p("# What was excluded, and what it cost")
    p()
    p(f"Generated by `scripts/report_exclusions.py` from `{data_path.name}`.")
    p()
    p("Delivers the two halves of a commitment fixed before the confirmatory run "
      "(`ANALYSIS_PLAN.md:191`, `state.md:435-436`) and not produced until 2026-08-15.")
    p()

    # ---- 1. headline counts ---------------------------------------------------------
    # Two denominators, because they answer different questions and quoting one as the other
    # is how `LIMITATIONS.md` came to say "2.0% of rows (43 of 1,302 cells)" -- where 2.0% is
    # the ROW share and 43/1,302 is 3.3%. Both numbers were right; the sentence was not.
    n_rows, n_excl = len(df), int(df.excluded.sum())
    keys = ["model", "condition", "foundation"]
    cells = df.groupby(keys)["excluded"].any()
    p("## 1. How much was dropped")
    p()
    p("| unit | total | excluded | share |")
    p("|---|---:|---:|---:|")
    p(f"| rows (model x condition x item) | {n_rows:,} | {n_excl:,} | {100 * n_excl / n_rows:.1f}% |")
    p(f"| cells (model x condition x foundation) | {len(cells):,} | {int(cells.sum()):,} | "
      f"{100 * cells.mean():.1f}% |")
    p(f"| models fully removed | {df.model.nunique()} | "
      f"{int(df.groupby('model')['excluded'].all().sum())} | — |")
    p()

    # A whole-model exclusion is a different act from a cell exclusion and must not be
    # averaged into the same percentage -- it is the researcher degree of freedom that
    # LIMITATIONS.md 22 exists to disclose.
    whole = df.groupby("model")["excluded"].all()
    whole = whole[whole].index.tolist()
    if whole:
        p(f"**{len(whole)} model(s) removed entirely**, which is a validity judgement rather "
          f"than a data-quality filter and is disclosed separately in `LIMITATIONS.md` 22: "
          f"{', '.join(whole)}.")
        p()
        p("Excluding those, the remaining exclusions are cell-level:")
        p()
        rest = df[~df.model.isin(whole)]
        rc = rest.groupby(keys)["excluded"].any()
        p(f"- rows: {int(rest.excluded.sum()):,} of {len(rest):,} "
          f"({100 * rest.excluded.mean():.1f}%)")
        p(f"- cells: {int(rc.sum()):,} of {len(rc):,} ({100 * rc.mean():.1f}%)")
        p()

    # ---- 2. by reason ---------------------------------------------------------------
    p("## 2. By reason")
    p()
    p("| reason | rows | cells |")
    p("|---|---:|---:|")
    ex = df[df.excluded].copy()
    ex["reason"] = ex["exclusion_reason"].astype(str).str.replace(r"\s+", " ", regex=True)
    # Collapse the parse-rate reasons, whose text carries the cell's own rate, so the table
    # groups by KIND of failure; the per-cell rates are in section 3.
    ex["kind"] = ex["reason"].str.replace(r"cell parse rate [\d.]+ < ([\d.]+)",
                                          r"cell parse rate < \1", regex=True)
    ex["kind"] = ex["kind"].str.replace(r"model discrimination.*", "model discrimination "
                                        "below 0.25x human between-item SD", regex=True)
    for kind, g in sorted(ex.groupby("kind"), key=lambda kv: -len(kv[1])):
        p(f"| {kind} | {len(g):,} | {g.groupby(keys).ngroups} |")
    p()

    # ---- 3. the table itself --------------------------------------------------------
    p("## 3. Every excluded cell, with its rate and reason")
    p()
    p("One row per excluded model x condition x foundation cell. `parse rate` is the cell's "
      "own share of items that produced a usable answer; the pre-specified threshold is 0.50 "
      "for the free-generation arms (`ANALYSIS_PLAN.md:189`).")
    p()
    if whole:
        p(f"Cells belonging to the {len(whole)} fully-removed model(s) are omitted here — they "
          f"would be every cell of that model, and the reason is identical for all of them.")
        p()
    tbl = df[df.excluded & ~df.model.isin(whole)]
    if tbl.empty:
        p("*No cell-level exclusions in this collection.*")
    else:
        p("| model | condition | foundation | items dropped | parse rate | reason |")
        p("|---|---|---|---:|---:|---|")
        g = tbl.groupby(keys)
        rows = []
        for (mdl, cond, fdn), sub in g:
            rate = sub["cell_parse_rate"].dropna()
            rows.append((mdl, cond, fdn, len(sub),
                         f"{rate.iloc[0]:.2f}" if len(rate) else "—",
                         str(sub["exclusion_reason"].iloc[0])))
        for mdl, cond, fdn, n, rate, reason in sorted(rows, key=lambda r: (r[0], r[1], r[2])):
            p(f"| {mdl} | {cond} | {fdn} | {n} | {rate} | {reason} |")
    p()

    # ---- 4. with and without --------------------------------------------------------
    p("## 4. R with and without the exclusions")
    p()
    p("The other half of the commitment. Both fits have existed in "
      f"`{vr_path.name}` since the refit; neither write-up document reported the pair.")
    p()
    if not vr_path.exists():
        p(f"*`{vr_path.name}` not found — run `analyse_variance_ratio.py` first.*")
    else:
        vr = pd.read_csv(vr_path)
        vr = vr[vr.residual == "method-specific"]
        p("Primary specification (method-specific residuals), cloze excluded.")
        p()
        p("| foundation | R, exclusions applied | R, no exclusions | change |")
        p("|---|---:|---:|---:|")
        for fdn, g in vr.groupby("foundation"):
            a = g[g.exclusions]
            b = g[~g.exclusions]
            if a.empty or b.empty:
                continue
            ra, rb = float(a.R_median.iloc[0]), float(b.R_median.iloc[0])
            star = " *(control)*" if bool(a.is_control.iloc[0]) else ""
            p(f"| {fdn}{star} | {ra:.3f} | {rb:.3f} | {100 * (rb - ra) / ra:+.0f}% |")
        p()
        both = [(float(g[g.exclusions].R_median.iloc[0]), float(g[~g.exclusions].R_median.iloc[0]))
                for _, g in vr.groupby("foundation")
                if not g[g.exclusions].empty and not g[~g.exclusions].empty]
        if both:
            ch = [100 * (b - a) / a for a, b in both]
            p(f"**Range: {min(ch):+.0f}% to {max(ch):+.0f}%.** This is a larger sensitivity "
              f"than either of the two `FINDINGS.md` 2 currently reports as \"the "
              f"sensitivities\" (scan-exclusion -20% to +3%; family effect -2% to +5%), which "
              f"is the reason for producing this table rather than only the fits.")
    p()

    out_path.write_text("\n".join(L), encoding="utf-8", newline="\n")
    print("\n".join(L))
    print(f"\nwrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
